### ISSUE TITLE
affect_frequencies returned with ambiguous keys

### ISSUE THREAD

**Issue by treize-khushrenada** [metalcorebear/NRCLex#7]
testing string: "give me money when in need"

when returning an NRCLex text object with .affect_frequencies::

{'fear': 0.0,
 'anger': 0.16666666666666666,
 **_'anticip': 0.0,_**
 'trust': 0.16666666666666666,
 'surprise': 0.16666666666666666,
 'positive': 0.16666666666666666,
 'negative': 0.0,
 'sadness': 0.0,
 'disgust': 0.0,
 'joy': 0.16666666666666666,
 'anticipation': 0.16666666666666666}

^ both 'anticip' and  'anticipation' were returned. I saw a recent change in the repo here would likely fix the problem. May I know when the next release date will be?

**Comment by metalcorebear** [comment]
Issue has been resolved.
